### ISSUE TITLE
Socket patch causing error on Windows with Python 2.7

### ISSUE THREAD

**Issue by davidkwast** [mleonhard/imapbackup#1]
Env: Python 2.7.3 (default, Apr 10 2012, 23:31:26) [MSC v.1500 32 bit (Intel)] on win32

Error:
Connecting to '**_' TCP port 143
Logging in as '**_'
Finding Folders: 10 folders
Folder INBOX:
Traceback (most recent call last):
  File "U:\Backup\IMAP\imapbackup.py", line 655, in <module>
    main()
  File "U:\Backup\IMAP\imapbackup.py", line 560, in main
    fol_messages = scan_folder(server, foldername)
  File "U:\Backup\IMAP\imapbackup.py", line 232, in scan_folder
    typ, data = server.fetch(num, '(BODY.PEEK[HEADER.FIELDS (MESSAGE-ID)])')
  File "C:\Python27\lib\imaplib.py", line 443, in fetch
    typ, dat = self._simple_command(name, message_set, message_parts)
  File "C:\Python27\lib\imaplib.py", line 1070, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "C:\Python27\lib\imaplib.py", line 897, in _command_complete
    typ, data = self._get_tagged_response(tag)
  File "C:\Python27\lib\imaplib.py", line 999, in _get_tagged_response
    self._get_response()
  File "C:\Python27\lib\imaplib.py", line 961, in _get_response
    data = self.read(size)
  File "C:\Python27\lib\imaplib.py", line 235, in read
    return self.file.read(size)
  File "U:\Backup\IMAP\imapbackup.py", line 624, in _fixed_socket_read
    buf_len = len(data)
TypeError: object of type 'cStringIO.StringO' has no len(

Solution:
 # Platform detection to enable socket patch
 #if 'Darwin' in platform.platform() and '2.3.5' == platform.python_version():
  #socket._fileobject.read = _fixed_socket_read
 #if 'Windows' in platform.platform():
  #socket._fileobject.read = _fixed_socket_read

Profit:
Connecting to '**_' TCP port 143
Logging in as '**_'
Finding Folders: 10 folders
Folder INBOX: 4007 messages
File INBOX.mbox: not found
Downloading 4007 new messages to INBOX.mbox: 317.243 MB total, 17.201 MB for largest message
Folder INBOX.Ag&AOo-ncias: 6 messages
File INBOX.Ag&AOo-ncias.mbox: not found
Downloading 6 new messages to INBOX.Ag&AOo-ncias.mbox: 3.707 MB total, 2.447 MB for largest message
Folder INBOX.Curriculos: 0 messages
File INBOX.Curriculos.mbox: not found
New messages: 0
Folder Lixo Eletr&APQ-nico: 0 messages
File Lixo Eletr&APQ-nico.mbox: not found
New messages: 0
Folder Drafts: 0 messages
File Drafts.mbox: not found
New messages: 0
Folder Trash: 0 messages
File Trash.mbox: not found
New messages: 0
Folder Itens Exclu&AO0-dos: 930 messages
File Itens Exclu&AO0-dos.mbox: not found
Downloading 930 new messages to Itens Exclu&AO0-dos.mbox: 261.748 MB total, 12.767 MB for largest message
Folder Junk: 0 messages
File Junk.mbox: not found
New messages: 0
Folder Sent: 0 messages
File Sent.mbox: not found
New messages: 0
Folder Itens Enviados: 1554 messages
File Itens Enviados.mbox: not found
Downloading 1554 new messages to Itens Enviados.mbox: 159.940 MB total, 22.492 MB for largest message
Disconnecting

**Comment by LOLLeela** [comment]
Ran into this problem myself, and your fix corrected it.

**Comment by davidkwast** [comment]
It was a monkey patch for old Python versions on Windows. This kind of patch must be more specific for those versions and never automatically continue working on future versions. Because bugs eventually get fixed.

**Comment by davidkwast** [comment]
Looks like it was fixed in 2.7: http://bugs.python.org/issue1441530 and http://bugs.python.org/issue1092502

**Comment by mleonhard** [comment]
This repo is superseded by https://github.com/rcarmo/imapbackup
